/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tenant-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTenantTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeTenantTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshTenantSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyTenants"];
        put?: never;
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenantMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteExistingTenantMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeTenantMember"];
        options?: never;
        head?: never;
        patch: operations["updateTenantMember"];
        trace?: never;
    };
    "/members/{membershipId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeTenantMemberRole"];
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateProject"];
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setProjectMember"];
        post?: never;
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{boardId}/tasks/{taskId}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["moveTask"];
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch: operations["updateTask"];
        trace?: never;
    };
    "/tasks/{taskId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["listComments"];
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResources"];
        put?: never;
        post: operations["uploadResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resourceQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["createResourceDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachResourceToTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markNotificationRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationPreferences"];
        put: operations["updateNotificationPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addPushSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push-subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removePushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenantId}/payment-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPaymentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhooks/fake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handleFakePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tenants/{tenantId}/provisioning/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryProvisioning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        /** Format: date-time */
        Instant: string;
        /** @enum {string} */
        TenantRole: "OWNER" | "ADMIN" | "MEMBER";
        /** @enum {string} */
        ProjectRole: "MANAGER" | "MEMBER" | "VIEWER";
        /** @enum {string} */
        TenantTier: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
        /** @enum {string} */
        TenantPlacement: "POOL" | "SILO_DATABASE";
        /** @enum {string} */
        TenantStatus: "PENDING_PAYMENT" | "PROVISIONING" | "ACTIVE" | "FAILED" | "SUSPENDED";
        /** @enum {string} */
        PaymentStatus: "CREATED" | "PENDING" | "SUCCEEDED" | "FAILED" | "EXPIRED";
        /** @enum {string} */
        ProvisioningStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "RETRYABLE_FAILED" | "FAILED_ROLLED_BACK";
        ApiError: {
            timestamp: components["schemas"]["Instant"];
            status: number;
            code: string;
            message: string;
            path: string;
            fieldErrors: {
                [key: string]: string;
            };
            requestId?: string | null;
        };
        UserView: {
            id: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            displayName: string;
        };
        TenantView: {
            id: components["schemas"]["UUID"];
            slug: string;
            name: string;
            tier: components["schemas"]["TenantTier"];
            status: components["schemas"]["TenantStatus"];
            placement: components["schemas"]["TenantPlacement"];
            role: components["schemas"]["TenantRole"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** Format: int64 */
            expiresInSeconds: number;
            user: components["schemas"]["UserView"];
            tenants: components["schemas"]["TenantView"][];
        };
        TenantTransferRequest: {
            tenantSlug: string;
        };
        TenantTransferResponse: {
            code: string;
            /** Format: uri */
            redirectUrl: string;
            /** Format: int64 */
            expiresInSeconds: number;
        };
        ExchangeRequest: {
            code: string;
        };
        TenantSessionResponse: {
            accessToken: string;
            /** Format: int64 */
            expiresInSeconds: number;
            user: components["schemas"]["UserView"];
            activeTenant: components["schemas"]["TenantView"];
        };
        MeResponse: {
            user: components["schemas"]["UserView"];
            tenant?: components["schemas"]["TenantView"] | null;
            tenantScoped: boolean;
        };
        CreateTenantRequest: {
            slug: string;
            name: string;
            tier: components["schemas"]["TenantTier"];
            placement: components["schemas"]["TenantPlacement"];
        };
        MemberView: {
            membershipId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["TenantRole"];
            active: boolean;
            /** Format: int64 */
            securityVersion: number;
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            role: components["schemas"]["TenantRole"];
        };
        UpdateMemberRequest: {
            role: components["schemas"]["TenantRole"];
            active: boolean;
        };
        ChangeRoleRequest: {
            role: components["schemas"]["TenantRole"];
        };
        DashboardView: {
            /** Format: int64 */
            projects: number;
            /** Format: int64 */
            boards: number;
            /** Format: int64 */
            openTasks: number;
            /** Format: int64 */
            overdueTasks: number;
            /** Format: int64 */
            unreadNotifications: number;
        };
        ProjectView: {
            id: components["schemas"]["UUID"];
            name: string;
            description?: string | null;
            createdBy: components["schemas"]["UUID"];
            createdAt: components["schemas"]["Instant"];
            updatedAt: components["schemas"]["Instant"];
            role: components["schemas"]["ProjectRole"];
            boardId?: components["schemas"]["UUID"] | null;
            /** Format: int64 */
            memberCount: number;
            /** Format: int64 */
            taskCount: number;
            /** Format: int64 */
            completedTaskCount: number;
        };
        CreateProjectRequest: {
            name: string;
            description?: string | null;
        };
        UpdateProjectRequest: components["schemas"]["CreateProjectRequest"];
        ProjectMemberView: {
            projectId: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            role: components["schemas"]["ProjectRole"];
        };
        SetProjectMemberRequest: {
            role: components["schemas"]["ProjectRole"];
        };
        ColumnView: {
            id: components["schemas"]["UUID"];
            name: string;
            position: number;
        };
        TaskView: {
            id: components["schemas"]["UUID"];
            projectId: components["schemas"]["UUID"];
            boardId: components["schemas"]["UUID"];
            columnId: components["schemas"]["UUID"];
            parentTaskId?: components["schemas"]["UUID"] | null;
            title: string;
            description?: string | null;
            assigneeUserId?: components["schemas"]["UUID"] | null;
            dueAt?: components["schemas"]["Instant"] | null;
            position: number;
            /** Format: int64 */
            version: number;
            createdAt: components["schemas"]["Instant"];
            updatedAt: components["schemas"]["Instant"];
        };
        BoardView: {
            id: components["schemas"]["UUID"];
            projectId: components["schemas"]["UUID"];
            name: string;
            columns: components["schemas"]["ColumnView"][];
            tasks: components["schemas"]["TaskView"][];
        };
        CreateBoardRequest: {
            name: string;
        };
        CreateTaskRequest: {
            columnId: components["schemas"]["UUID"];
            parentTaskId?: components["schemas"]["UUID"] | null;
            title: string;
            description?: string | null;
            assigneeUserId?: components["schemas"]["UUID"] | null;
            dueAt?: components["schemas"]["Instant"] | null;
            position?: number | null;
        };
        UpdateTaskRequest: {
            columnId: components["schemas"]["UUID"];
            title: string;
            description?: string | null;
            assigneeUserId?: components["schemas"]["UUID"] | null;
            dueAt?: components["schemas"]["Instant"] | null;
            position?: number | null;
            /** Format: int64 */
            version: number;
        };
        MoveTaskRequest: {
            targetColumnId: components["schemas"]["UUID"];
            targetPosition: number;
            /** Format: int64 */
            version: number;
        };
        CommentView: {
            id: components["schemas"]["UUID"];
            taskId: components["schemas"]["UUID"];
            authorUserId: components["schemas"]["UUID"];
            body: string;
            createdAt: components["schemas"]["Instant"];
        };
        CreateCommentRequest: {
            body: string;
        };
        ResourceView: {
            id: components["schemas"]["UUID"];
            originalName: string;
            /** @description Server-generated key; clients must not use it for authorization */
            storageKey: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            uploadedBy: components["schemas"]["UUID"];
            createdAt: components["schemas"]["Instant"];
            /** Format: int64 */
            taskCount: number;
        };
        QuotaView: {
            /** Format: int64 */
            usedBytes: number;
            /** Format: int64 */
            limitBytes: number;
        };
        DownloadUrl: {
            /** Format: uri-reference */
            url: string;
            expiresAt: components["schemas"]["Instant"];
        };
        NotificationView: {
            id: components["schemas"]["UUID"];
            eventType: string;
            title: string;
            body: string;
            readAt?: components["schemas"]["Instant"] | null;
            createdAt: components["schemas"]["Instant"];
        };
        NotificationPreferences: {
            inAppEnabled: boolean;
            emailEnabled: boolean;
            webPushEnabled: boolean;
        };
        PushSubscriptionRequest: {
            /** Format: uri */
            endpoint: string;
            p256dh: string;
            auth: string;
        };
        PushSubscriptionView: {
            id: components["schemas"]["UUID"];
            /** Format: uri */
            endpoint: string;
            createdAt: components["schemas"]["Instant"];
        };
        AuditView: {
            id: components["schemas"]["UUID"];
            actorUserId?: components["schemas"]["UUID"] | null;
            actorName: string;
            action: string;
            aggregateType: string;
            aggregateId?: components["schemas"]["UUID"] | null;
            correlationId?: string | null;
            detailsJson: string;
            occurredAt: components["schemas"]["Instant"];
        };
        CreatePaymentRequest: {
            /** Format: int64 */
            amountMinor: number;
            currency: string;
            /** Format: uri */
            returnUrl: string;
        };
        PaymentSessionView: {
            paymentId: components["schemas"]["UUID"];
            provider: string;
            reference: string;
            /** Format: uri */
            checkoutUrl: string;
            status: components["schemas"]["PaymentStatus"];
        };
        PaymentResultView: {
            paymentId: components["schemas"]["UUID"];
            tenantId: components["schemas"]["UUID"];
            status: components["schemas"]["PaymentStatus"];
            duplicate: boolean;
        };
        AdminTenantView: {
            id: components["schemas"]["UUID"];
            name: string;
            slug: string;
            tier: components["schemas"]["TenantTier"];
            placement?: components["schemas"]["TenantPlacement"] | null;
            status: components["schemas"]["TenantStatus"];
            provisioningStatus?: components["schemas"]["ProvisioningStatus"] | null;
            /** Format: int64 */
            memberCount: number;
            createdAt: components["schemas"]["Instant"];
            lastError?: string | null;
        };
        AdminTenantPage: {
            items: components["schemas"]["AdminTenantView"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
    };
    responses: {
        /** @description Structured API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        CsrfHeader: string;
        OptionalCsrfHeader: string;
        TenantId: components["schemas"]["UUID"];
        MembershipId: components["schemas"]["UUID"];
        UserId: components["schemas"]["UUID"];
        ProjectId: components["schemas"]["UUID"];
        BoardId: components["schemas"]["UUID"];
        TaskId: components["schemas"]["UUID"];
        ResourceId: components["schemas"]["UUID"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Global session and available tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTenantTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantTransferRequest"];
            };
        };
        responses: {
            /** @description One-time transfer code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantTransferResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exchangeTenantTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description Tenant-bound access token; refresh and CSRF cookies are set */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshTenantSession: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated tenant session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["OptionalCsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh session revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and optional tenant context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMyTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active memberships of current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant in PENDING_PAYMENT state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTenantMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active tenant members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    inviteExistingTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Membership created or reactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Updated membership and incremented security version when changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changeTenantMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Updated membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics restricted to projects visible to current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects with current user's project membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project, manager membership and default Kanban board created atomically */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listProjectMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProjectMemberRequest"];
            };
        };
        responses: {
            /** @description Project membership created or updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project membership removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description Board with default columns */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board, columns and tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    moveTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boardId: components["parameters"]["BoardId"];
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveTaskRequest"];
            };
        };
        responses: {
            /** @description Task moved; 409 is returned for stale version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated; 409 is returned for stale version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources uploaded by or project-visible to current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Resource stored in tenant namespace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resourceQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate quota for tenant administrators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createResourceDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived authorized URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrl"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    attachResourceToTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: components["parameters"]["ResourceId"];
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource attached idempotently */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated notification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All current user's notifications marked read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferences"];
            };
        };
        responses: {
            /** @description Updated notification preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Push subscription stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removePushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Push subscription removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant audit events for tenant administrators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditView"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPaymentSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequest"];
            };
        };
        responses: {
            /** @description Idempotent provider checkout session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSessionView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    handleFakePaymentWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Payment-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Verified and idempotently processed callback */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResultView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAdminTenants: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Control-plane tenant page for system administrators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTenantPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    retryProvisioning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Failed job queued again and transition audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
